import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeadePager from "./components/HeaderPager";
import FooterPage from "./components/FooterPage";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OdinClub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mx-0 sm:mx-5">
      <HeadePager />
      <main className="">{children}</main>

      <FooterPage />

      <Footer />
    </div>
  );
}
