import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShopContextProvider from "./context/Context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "aos/dist/aos.css";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale(); // Lấy locale từ server

  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ToastContainer />
        {/* Bao bọc NextIntlClientProvider */}
        <NextIntlClientProvider locale={locale}>
          <ShopContextProvider>{children}</ShopContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
