import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ShopContextProvider from "./context/Context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "aos/dist/aos.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <ToastContainer />
        <ShopContextProvider>{children}</ShopContextProvider>
      </body>
    </html>
  );
}
