import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderProfile from "./components/headerProfile";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quản Lý Thông Tin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" className="flex h-screen">
      <div className="w-1/6 border-r ">
        <HeaderProfile />
      </div>
      <main className={`w-5/6`}>{children}</main>
    </div>
  );
}
